spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: user
      authentication-database: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: user-service

server:
  port: 8090
