spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mnaffeti/config-server.git
          username: Mnaffeti
          password: ${MY_SECRET_TOKEN}
          default-label: main
          clone-on-start: true
server:
  port: 8888